### ISSUE TITLE
Localization Issue with Comma vs Period Based Decimal Separator

### ISSUE THREAD

**Issue by AndrewHazelden** [Kartaverse/Spatial-Metadata#2]
There is a known localization issue with the current Spatial Metadata GUI's v1.1 release's handling of textfield based number entry in the GUI for users in select regions with non "English US" region settings enabled in their OS. Dev efforts are underway now to solve this. :)

At the moment, you need to set your computer's localization settings to allow a period based separator to be used for the decimal point mark. If you have your number input preferences in your operating system set to use a comma value for the decimal point character there will be an error.

Summary: The GUI wrapper tool is a thin shell that is passing data to the Spatial CLI tool through the command line interface. A North American localized number input setting has to be used until the next dot update is shipped. (Sorry about that!)

**Comment by mrlando** [comment]
Hi Andrew,

Excellent work on this app, makes it much easier to create spatial videos.
The only thing is this issue with the comma vs period. Now I constantly need to switch the region back and forth.
Any idea when you are going to fix this?

MrLando

**Comment by AndrewHazelden** [comment]
> Any idea when you are going to fix this?

As soon as a I have a spare moment I will fix this. It's at the absolute top of my priority list.

**Comment by mrlando** [comment]
Great! 👍

**Comment by AndrewHazelden** [comment]
@mrlando There is a new v1.2 update that addresses the comma vs period localization issue. Please let me know if you try it out and it works for you: https://github.com/Kartaverse/Spatial-Metadata/releases/tag/v1.2

**Comment by mrlando** [comment]
Yes! It works! Appreciated thx!
Can I make a suggestion? Can you make a progress bar instead of the raw output text? Or at least let it auto scroll to the last line every time so I do not need to scroll to see the progress? When you have time for this ofc.

**Comment by AndrewHazelden** [comment]
The Xojo code for auto-scrolling the console zone to the last line of text is already present in the source code in the repo. It was simply commented out due to having some scrollback view refreshing issues that needed resolving when the text input line was also used.

![Scroll to Bottom](https://github.com/user-attachments/assets/6132e829-f7f7-430e-a4f2-5d7cf17b6f4b)

**Comment by mrlando** [comment]
Ok, well I'll just scroll a bit for now. It is converting to spatial at least. It would be a nice addition sometime in the future.

**Comment by AndrewHazelden** [comment]
Yup. I will enable a progress bar and scrolling console view feature on the next dot update of the Spatial Metadata GUI toolset, along with spatial photo conversions, and a JSON based preset system. :)

**Comment by mrlando** [comment]
Awesome!
